###
GET http://localhost:3000/produtos HTTP/1.1

###
GET http://localhost:3000/produtos/1 HTTP/1.1

###
POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json

{
"nome": "Produto 1",
 "preco": 10.00,
 "emailEmpresa": "teste@mail.com",
 "dataValidade": "2025-06-12"
}

###
PATCH http://localhost:3000/produtos/1 HTTP/1.1
Content-Type: application/json

{
  "nome": "Produto 2",
  "preco": 9.00
}

###
DELETE http://localhost:3000/produtos/1 HTTP/1.1
